### ISSUE TITLE
Output in Powershell not imported as txt file

### ISSUE THREAD

**Issue by neurotic-jm** [the-light-yagami/IMDB_info_filter#1]
Output in Powershell not imported as txt file.

Please check.

**Comment by the-light-yagami** [comment]
you mean if you create a text file with powershell (movie list) then its not imported as text file ??

**Comment by neurotic-jm** [comment]
Thanks for getting back. I ran the script and it is showing the description, movie name, date and etc on the powershell but when i go to the .txt file per movie, which was automatically created by the program, each and everyone of them is blank.

**Comment by the-light-yagami** [comment]
I think ( https://www.youtube.com/watch?v=XhCJxJGqK2o ) this video will help you. The script run fine at my machine, it will be better if you contact with me on hangout (aamiabid@gmail.com), then i come remotely on your pc and may solve the problem, but first please check the application dependency, it depends on python 3x (i use 3.4.3) and bs4,requests external module.
